== PB315


+*In[9]:*+
[source, ipython3]
----
s1 = input("Enter first name : ")
s2 = input("Enter second name : ")
if len(s1) == len(s2):
    if sorted(s1)==sorted(s2):
        print("balance ")
    else:
        print("not balance ")
else:
    print("not balance ")
----


+*Out[9]:*+
----
Enter first name :  hello
Enter second name :  ooohj

not balance 
----

== PB314


+*In[12]:*+
[source, ipython3]
----
s1 = input("Enter name : ")
s2 = int(input("Enter shift : "))
result = ""
for char in s1:
    if char.isupper():
        result+=chr((ord(char)- 65 + s2) % 26 + 65)
    elif char.islower():
        result+=chr((ord(char)- 97 + s2) % 26 + 97)
    else:
        result+=char
print(result)
----


+*Out[12]:*+
----
Enter name :  LJIET ENG
Enter shift :  3

OMLHW HQJ
----

== PB 313


+*In[18]:*+
[source, ipython3]
----
x = input("Enter name : ")
result = ""
for char in x:
    if "a"<= char <="z":
        result+=chr(ord(char)-32)
    elif "A"<= char <="Z":
        result+=chr(ord(char)+32)
    else:
        result+=char
print(result)
----


+*Out[18]:*+
----
Enter name :  Mr.Ed

mR.eD
----

== PB 312


+*In[25]:*+
[source, ipython3]
----
def password(text):
    if len(text) < 8:
        return False
    has_uppercase = False
    has_lowercase = False
    has_digit = False
    has_special = False
    special = "_@#$"
    for ch in text:
        if ch.isupper():
            has_uppercase = True
        elif ch.islower():
            has_lowercase = True
        elif ch.isdigit():
            has_digit = True
        elif ch in special:
            has_special = True
        else:
            return False 
    return has_uppercase and has_lowercase and has_digit and has_special 
x = input("Enter password : ")
if password(x):
    print(x,"this is valid 🥳")
else:
    print("Enter valid password ")
----


+*Out[25]:*+
----
Enter password :  kano@1

Enter valid password 
----

== PB 311


+*In[27]:*+
[source, ipython3]
----
x = input("Enter name to find latter ")
uppercase = 0
lowercase = 0
digit = 0
for char in x:
    if char.isupper():
        uppercase+=1
    elif char.islower():
        lowercase+=1
    elif char.isdigit():
        digit+=1
    else:
        print("not latter and number found ")
print("Upper case ",uppercase)
print("lowercase ",lowercase)
print("digit ",digit)
----


+*Out[27]:*+
----
Enter name to find latter  KANOSsolanki122344

Upper case  5
lowercase  7
digit  6
----

# PB 310


+*In[39]:*+
[source, ipython3]
----
x = input("Enter number : ")
y = int(input("Enter shift : "))
length = len(x)
if y > length:
    print(x[::-1])
else:
    y = y % length 
    result = x[y:]+x[:y]
    print(result)
----


+*Out[39]:*+
----
Enter number :  1234
Enter shift :  3

4123
----

== PB 309


+*In[40]:*+
[source, ipython3]
----
t = (23,34,45,56,67,78,89)
even = 0
odd = 0 
for num in t:
    if num%2==0:
        even += num
    else:
        odd += num
print("even number : ",even)
print("odd number : ",odd)
----


+*Out[40]:*+
----
even number :  168
odd number :  224
----

== PB 308


+*In[41]:*+
[source, ipython3]
----
t = (10, 21, 4, 33, 6, 7, 90, 11)

print("Even numbers:")
for num in t:
    if num % 2 == 0:
        print(num, end=" ")
----


+*Out[41]:*+
----
Even numbers:
10 4 6 90 ----

== PB 395


+*In[48]:*+
[source, ipython3]
----
def fun(x):

    length = len(x)
    even_sum = 0
    odd_sum = 0
    for i in range(length):
        if i%2==0:
            even_sum += x[i]
        else:
            odd_sum += x[i]
    count = 0 
    left_odd = 0
    left_even = 0 
    for i in range(length):
        if i%2==0:
            even_sum -= x[i]
        else:
            odd_sum -= x[i]
        if odd_sum + left_even == even_sum + left_odd:
            count+=1
        if i%2==0:
            left_even += x[i]
        else:
            left_odd += x[i]
    return count
A1 = [2, 1, 6, 4]
A2 = [5, 5, 2, 5, 8]
print(fun(A1))
print(fun(A2))
----


+*Out[48]:*+
----
1
2
----

== PB 396


+*In[52]:*+
[source, ipython3]
----
n = int(input("Enter number to syracuse : "))
while n != 1:
    print(n,end = " ")
    if n % 2 == 0:
        n = n // 2
    else:
        n = n*3+1
print(1)
----


+*Out[52]:*+
----
Enter number to syracuse :  5

5 16 8 4 2 1
----

== PB 454


+*In[61]:*+
[source, ipython3]
----
def valid(s):
    stack = []
    pairs = {')':'(',']':'[','}':'{'}
    for ch in s:
        if ch in "({[":
            stack.append(ch)
        elif ch in ")}]":
            if not stack or stack[-1] != pairs[ch]:
                return False 
            stack.pop()
    return len(stack)==0
x = input("Enter valid pairs : ")
if valid(x):
    print("valid")
else:
    print("not valid ")
----


+*Out[61]:*+
----
Enter valid pairs :  {}()[]

valid
----

== PB 453


+*In[67]:*+
[source, ipython3]
----
x = list(map(int,input("Enter list : ").split()))
y = len(x)
for i in range(1,y,2):
    temp = x[-1]
    for j in range(y-1,i,-1):
        x[j] = x[j-1]
    x[i] = temp
print(f"list is {x}")
----


+*Out[67]:*+
----
Enter list :  2 3 4 5 6

list is [2, 6, 3, 5, 4]
----

== PB 452


+*In[73]:*+
[source, ipython3]
----
x = list(map(int,input("Enter list ").split()))
shift = int(input("Enter shift "))
length = len(x)
if shift > length:
    print(x[::-1])
else:
    shift = shift%length 
    result = x[shift:] + x[:shift]
    print(result)
----


+*Out[73]:*+
----
Enter list  1 2 3 4 5
Enter shift  3

[4, 5, 1, 2, 3]
----

== PB 451


+*In[78]:*+
[source, ipython3]
----
num = list(map(int , input("Enter list of number ;").split()))
length = len(num)
sum1 = 0
for ch in num:
    if ch == 13:
       continue
    sum1 += ch
print(f"sum of list: {sum1}")
    
----


+*Out[78]:*+
----
Enter list of number ; 1 2 3 13 4 5

sum of list: 15
----

== PB 450 in construction


+*In[2]:*+
[source, ipython3]
----
d = {
    "student0": 'Student@0',
    "student1": 'Student@11',
    "student2": 'Student@121',
    "student3": 'Student@052',
    "student4": 'Student@01278',
    "student5": 'Student@0125',
    "student6": 'Student@042',
    "student7": 'Student@07800',
    "student8": 'Student@012'
}
# login for username and password
attempt = 3
valid_both = None
while attempt > 0: 
    user = input("Enter username : ")
    pw = input("Enter password : ")
    if user in d and d[user] == pw:
        valid_both = user 
        break
    else:
        print("Enter valid password and username :")
        attempt -= 1
if not valid_both:
    print("Your trial are finish :")
    print("try after 24 hour :")
    exit()
# new password
def valid(pw):
    pw_len = len(pw)
    if pw_len < 8 or 15 < pw_len:
        print("Enter valid password in 8 to 15 latter ")
        return False
    has_upper = False
    has_lower = False
    has_digit = False 
    special = "@$_"
    has_special = False
    for ch in pw:
        if ch.isupper():
            has_upper = True
        elif ch.islower():
            has_lower = True 
        elif ch.isdigit():
            has_digit = True 
        elif ch in special:
            has_special = True
        else:
            print("Enter valid password ")
    if not (ch.isalnum() or ch in special):
        return False
    if has_upper and has_lower and has_digit and has_special:
        return True
attempt_p = 3
while attempt_p > 0:
    passs = input("New Enter password ")
    if valid(passs):
        d[valid_both] = passs
        print("new password update ")
        break
    else:
        print("Enter valid ")
        attempt_p-=1
if attempt_p == 0:
    print("Enter valid new password ")
    print("try after 24 hours ")
    exit()

----


+*Out[2]:*+
----
Enter username :  ashdfgj
Enter password :  sdhfg

Enter valid password and username :

Enter username :  sdkjfh
Enter password :  sdfjgh

Enter valid password and username :

Enter username :  skjdhfkjs
Enter password :  jhgsdf

Enter valid password and username :
Your trial are finish :
try after 24 hour :

New Enter password  Kanos @123

Enter valid password 
new password update 
----

== PB 449


+*In[5]:*+
[source, ipython3]
----
x = input("Enter syntax :")
w = x.split()
d = {}
for ch in w:
    key = ch[0]
    if key not in d:
        d[key] = []
    d[key].append(ch)
print(d)
----


+*Out[5]:*+
----
Enter syntax : this is my life but this is not other life my rule

{'t': ['this', 'this'], 'i': ['is', 'is'], 'm': ['my', 'my'], 'l': ['life', 'life'], 'b': ['but'], 'n': ['not'], 'o': ['other'], 'r': ['rule']}
----

== PB 447


+*In[10]:*+
[source, ipython3]
----
x =  ['abc', 'xyz', 'aba', '2112', '123451', '12345']
count = 0
for ch in x:
    if len(ch)>=3 and ch[0]==ch[-1]:
        count += 1
print("output : ",count)
----


+*Out[10]:*+
----
output :  3
----

== PB 445


+*In[15]:*+
[source, ipython3]
----
x = input("Enter String ")
w = x.lower().split()
d = {}
for ch in w:
    if ch in d:
        d[ch] +=1
    else:
        d[ch] = 1
print(d)
    
----


+*Out[15]:*+
----
Enter String  this is ,jbcvbcb

{'this': 1, 'is': 1, ',jbcvbcb': 1}
----

== PB 444


+*In[24]:*+
[source, ipython3]
----
def pw(x):
    if len(x)<8:
        return False
    has_upper = False 
    has_lower = False
    has_digit = False
    for ch in x:
        if ch.isupper():
            has_upper = True
        elif ch.islower():
            has_lower = True
        elif ch.isdigit():
            has_digit = True
        else:
            return False
    if has_upper and has_lower and has_digit:
        return True 
passs = input("Enter password :")
if pw(passs):
    print("valid : ",passs)
else:
    print('invalid password')
    

----


+*Out[24]:*+
----
Enter password : Kanos123

valid :  Kanos123
----

== PB 443


+*In[27]:*+
[source, ipython3]
----
m = [2, 4, -6, -9, 11, -12, 14, -5, 17]
positive = list(filter(lambda x : x>0,m))
negative = list(filter(lambda x : x<0 , m))
sum_pt = sum(positive)
sum_nt = sum(negative)
print("positive : ",sum_pt)
print("negative : ",sum_nt)
----


+*Out[27]:*+
----
positive :  5
negative :  4
----

== PB 439


+*In[33]:*+
[source, ipython3]
----
x =  ["lessonplan", "lesson","lees", "length"]
y =  ["python","pythonprogramming","pythonlist"]
x.sort()
y.sort()
first = x[0]
last = x[-1]
prefix  = ""
for i in range(min(len(first),len(last))):
    if first[i] == last[i]:
        prefix += first[i]
    else:
        break
if prefix :
    print(prefix)
else:
    print(-1)
----


+*Out[33]:*+
----
python
----

== PB 436


+*In[37]:*+
[source, ipython3]
----
numbers = [13, 19, 26, 38, 39, 57, 76, 95, 100, 114, 152,45]

result = list(filter(lambda x: x % 13 == 0 or x % 19 == 0, numbers))

print("Numbers divisible by 13 or 19:", result)
----


+*Out[37]:*+
----
Numbers divisible by 13 or 19: [13, 19, 26, 38, 39, 57, 76, 95, 114, 152]
----


+*In[ ]:*+
[source, ipython3]
----

----
